platform: library: Add missing include task.h to ll_schedule
This fixes build issues

In file included from tools/testbench/common_test.c:5:
src/platform/library/include/platform/lib/ll_schedule.h:22:51:
error: ‘enum task_state’ declared inside parameter list will not
be visible outside of this definition or declaration [-Werror]

In file included from tools/testbench/common_test.c:16:
tools/testbench/build_testbench/sof_ep/install/include/sof/
schedule/ll_schedule.h:40:5:
error: conflicting types for ‘schedule_task_init_ll’

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>