Audio: Volume: Remove two unused variables from peakvolume
The remove of variables in1 and out1 in peakvolume HiFi4
function vol_s16_to_s16() avoids testbench IPC4 build error:

sof/src/audio/volume/volume_hifi4_with_peakvol.c:406:10:
error: unused variable 'in1' [-Werror,-Wunused-variable]

sof/src/audio/volume/volume_hifi4_with_peakvol.c:407:10:
error: unused variable 'out1' [-Werror,-Wunused-variable]

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>