Audio: Crossover: Fix IPC4 testbench build
The crossover_init_output_pins() function is changed to static.
This change avoids build error:

sof/src/audio/crossover/crossover_ipc4.c:32:5:
error: no previous prototype for ‘crossover_init_output_pins’
[-Werror=missing-prototypes]

Signed-off-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>